name = "brush"
version = "0.2.19"
licenses = ["MIT"]
description = "ğŸšbash/POSIX-compatible shell implemented in Rust ğŸ¦€"
repository = "https://github.com/reubeno/brush"
branch = "brush-shell-v0.2.19"